### PR TITLE
Convert to es modules

### PR DESCRIPTION
**Pull request by anonrose**
Hey all, love the product! This is larger than it seems, only took me about half an hour. This package is a bit behind the times( offense not intended ). If this is merged it'll open up my removal of request PR as it's now [deprecated](https://medium.com/better-programming/request-has-been-deprecated-a76415b4910b), also it migrates to async await.

Addresses https://github.com/alpacahq/alpaca-trade-api-js/issues/83

### CODE REVIEW

**Comment by anonrose** [comment]
Hoping to get a review some time soon as I want to know if I should continue with my fork. Thanks!

**Comment by neeschit** [comment]
Hey @anonrose, when @shlomikushchi and I spoke, he mentioned backwards compatibility would be important. That is to say, CommonJS users should continue to be able to use CommonJS. While your changes move this module over to ESM, it would break backwards compatibility for projects using CJS moving forward.

We'll likely need to publish a hybrid npm module that allows both CJS and ESM/MJS while maintaining backwards compatibility.

**Comment by anonrose** [comment]
ES modules allow you to import common JS, but Common JS doesn't allow the importing of ES modules. Making a backwards compatible version might be more work for this reason. Bumping the major version to 2.0 and moving forward with ES modules is an alternative, if not I personally won't be opening a PR supporting common JS. Let me know what you guys think and I can close this and continue in my own repo.

**Comment by anonrose** [comment]
Closing this and using https://github.com/117/alpaca per @neeschit's comment in https://github.com/alpacahq/alpaca-trade-api-js/issues/83

**Pull request closed without merging**
